name: Train

on:
  workflow_dispatch:

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t crystalvalue-train .

      - name: Create credentials file
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' > gcp_credentials.json
          chmod 600 gcp_credentials.json

      - name: Run Docker Container
        run: |
          docker run \
            -e GOOGLE_APPLICATION_CREDENTIALS=/app/gcp_credentials.json \
            -v $(pwd)/gcp_credentials.json:/app/gcp_credentials.json \
            crystalvalue-train 